name: Echo Hello

on:
  pull_request:
      branches: [main]
    
jobs:
  echo-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Echo Hello
        run: echo "asdf!"
