name: Echo Hello

on:
  pull_request:
      branches: [main]
    
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Echo Hello
        run: echo "${{ secrets.TEST_ENV }}" | base64 
