name: Echo Hello

on:
  push:
  pull_request:
      branches: [main]
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo Hello
        run: echo "Hello!"
