name: CI
on:
  workflow_call:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]
  

jobs:
  commands:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3   
      - name: Run command
        run: 
          ls -la
