name: CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  commands:
    name: Test
    runs-on: ubuntu-20.04
    environment: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run command
        run:
          cd ~/;
          echo 'tester' > tester.txt;
          ls -la;
      - name: cacher
        uses: actions/cache@v3
        with:
          path: ~/
          key: workflow
          restore-keys: |
            otherworkflow
      
        
