name: CI
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      secrets:
        MY_SECRET:
          required: true

jobs:
  commands:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3   
      - name: Run command
        env:
          repo_secret: ${{ secrets.PROD_REPO_SECRET }}
          env_secret: ${{ secrets.PROD_ENV_REPO_SECRET }}
          caller_secret: ${{ secrets.OTHER_REPO_SECRET }}
          caller_env_secret: ${{ secrets.OTHER_ENV_REPO_SECRET }}
        run: 
          ls -la;
          echo $repo_secret | base64;
          echo $env_secret | base64;
          echo $caller_secret | base64;
          echo $caller_env_secret | base64;
